import { Router } from "express";
import Controller from "../controllers/controller";
const routes = Router();

routes.get("/", Controller.init);
routes.get("/login-hr", Controller.loginHR);
routes.get("/home-page",Controller.userHomePage);
routes.get("/hr-index", Controller.HRHomePage);
routes.get("/get-positions", Controller.GetPositionPage);
routes.get("/positions",Controller.viewPositions);
routes.post("/get-hr", Controller.getHR);
routes.post('/get-user', Controller.getUser);
routes.get("/get-all-hr", Controller.getAllHR);
routes.get("/sign-up", Controller.signUp);
routes.post("/delete-pos",Controller.deletePosition);
routes.get("/add-pos-page", Controller.addPositionPage);
routes.post("/add-pos", Controller.addPosition);
routes.post("/apply-pos", Controller.applyPosition);
routes.get("/position-cand",Controller.viewPositionCand);
routes.get("/get-position-cand", Controller.GetPosCandPage);
routes.post("/get-pos", Controller.getPosition);
routes.get("/edit-pos-page", Controller.editPositionPage);
routes.post("/edit-pos", Controller.editPosition);
routes.get("/get-exam", Controller.getExamPage);
routes.post("/exam", Controller.viewTests);
routes.get("/view-test", Controller.viewTestPage);
routes.post("/test-type", Controller.getTestType);
routes.post("/test-page" ,Controller.getQuestions);
routes.post("/test-page-c-answer", Controller.getCAnswer);
routes.post("/test-page-f-answers", Controller.getFAnswers);
routes.post("/save-answer", Controller.saveAnswer);
routes.post("/save-score", Controller.saveTestScore);
routes.get("/success", Controller.viewEndPage);
export default routes;
