import { Router } from "express";
import Controller from "../controllers/controller";
const routes = Router();
routes.get("/", Controller.init);
routes.get("/loginhr", Controller.loginHR);
routes.get("/homePage",Controller.viewHomePage);
routes.get("/Positions",Controller.viewPositions);
routes.post("/getHR", Controller.getHR);
routes.get("/getAllHR", Controller.getAllHR);
export default routes;
